# configures the application name, graceful shutdown and external transcription settings.

spring.application.name=Assignment1

# api
openai.api.key=${OPENAI_API_KEY:}
openai.transcription.url=${OPENAI_TRANSCRIPTION_URL:https://api.openai.com/v1/audio/transcriptions}

# shutdown
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=5s